---
version: "3.9"
services:
  the-atlas:
    image: bansheetech/atlas:latest
    container_name: the-atlas
    ports:
      - "42424:5000"
    volumes:
      - /DATA/HomeDock/the-atlas:/app
      # - /your_ssl_cert:/app/ssl # optional SSL certs directory
    restart: always
